version: '3.2'

services:
  tomcat_kt:
    container_name: tomcat_kinotop
    build: .
    volumes:
      - ../build/libs/kinotop-0.1.war:/usr/local/tomcat/webapps/ROOT.war

  mysql_kt_java:
    ports:
      - 33065:3306
    image: mysql:5.7
    container_name: mysql_kinotop
    volumes:
      - mysql_kt_java_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql # Dump will be imported on first start
    command: mysqld --sql-mode='' --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=kinotop
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"

  nginx_kt:
    image: nginx:latest
    container_name: nginx_kinotop
    ports:
      - 8005:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  mysql_kt_java_data: {}
